import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-secondary': '#003640',
        'inverse-primary': '#005ac2',
        'on-secondary-container': '#00424e',
        'secondary-fixed-dim': '#4cd7f6',
        'on-secondary-fixed-variant': '#004e5c',
        primary: '#adc6ff',
        'on-surface': '#d4e4fa',
        'on-primary': '#002e6a',
        'primary-container': '#4d8eff',
        'on-tertiary-fixed-variant': '#930013',
        'surface-container-low': '#0d1c2d',
        'secondary-container': '#03b5d3',
        'surface-container-lowest': '#010f1f',
        'outline-variant': '#424754',
        'inverse-on-surface': '#233143',
        'surface-container': '#122131',
        'inverse-surface': '#d4e4fa',
        'on-error': '#690005',
        'tertiary-fixed-dim': '#ffb3ad',
        error: '#ffb4ab',
        'on-tertiary': '#68000a',
        'on-error-container': '#ffdad6',
        'surface-dim': '#051424',
        'tertiary-container': '#ff5451',
        background: '#051424',
        'on-primary-fixed': '#001a42',
        'on-tertiary-container': '#5c0008',
        'secondary-fixed': '#acedff',
        tertiary: '#ffb3ad',
        'surface-variant': '#273647',
        'surface-tint': '#adc6ff',
        'primary-fixed': '#d8e2ff',
        'on-secondary-fixed': '#001f26',
        'surface-container-high': '#1c2b3c',
        'surface-bright': '#2c3a4c',
        'tertiary-fixed': '#ffdad7',
        surface: '#051424',
        'primary-fixed-dim': '#adc6ff',
        'on-primary-fixed-variant': '#004395',
        'on-primary-container': '#00285d',
        'surface-container-highest': '#273647',
        'on-background': '#d4e4fa',
        'on-surface-variant': '#c2c6d6',
        secondary: '#4cd7f6',
        'error-container': '#93000a',
        outline: '#8c909f',
        'on-tertiary-fixed': '#410004',
      },
      fontFamily: {
        'display-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
        'data-mono': ['JetBrains Mono', 'monospace'],
        'body-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'label-caps': ['11px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-sm': ['18px', { lineHeight: '1.4', fontWeight: '600' }],
        'data-mono': ['13px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '500' }],
        'body-md': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        xs: '8px',
        base: '4px',
        lg: '32px',
        md: '24px',
        'margin-mobile': '16px',
        sm: '16px',
        gutter: '20px',
        'margin-desktop': '32px',
        xl: '48px',
      },
    },
  },
  plugins: [],
}
export default config