'use client'

import { useEffect, useState } from 'react'
import { queryAgent } from '@/lib/api'
import { getOrCreateSessionId, resetSessionId } from '@/lib/session'

const quickActions = ['Show ICU occupancy', 'Summarize shift notes', 'Flag abnormal vitals']
type Message = { role: 'user' | 'agent'; content: string; time: string }
export default function AIAgentPage() { const [messages,setMessages] = useState<Message[]>([{role:'agent',content:'Hello. I am your VITAL_OS Clinical Assistant. How can I help you today?',time:new Date().toLocaleTimeString()}]); const [input,setInput]=useState(''); const [loading,setLoading]=useState(false); const [sessionId,setSessionId]=useState('')
  useEffect(()=>setSessionId(getOrCreateSessionId()),[])
  const sendMessage = async (value = input) => { if (!value.trim() || loading || !sessionId) return; setMessages((m)=>[...m,{role:'user',content:value,time:new Date().toLocaleTimeString()}]); setInput(''); setLoading(true); try { const response=await queryAgent(value,sessionId); setMessages((m)=>[...m,{role:'agent',content:response.response || 'No response',time:new Date().toLocaleTimeString()}]) } catch (error:any) { setMessages((m)=>[...m,{role:'agent',content:`Error: ${error.message}`,time:new Date().toLocaleTimeString()}]) } finally { setLoading(false) } }
  const newSession=()=>{setSessionId(resetSessionId());setMessages([{role:'agent',content:'New session started. Earlier patient context has been cleared.',time:new Date().toLocaleTimeString()}])}
  return <div><div className="page-heading"><div><p className="section-label">Clinical intelligence</p><h1>AI clinical assistant</h1><p>Ask questions about hospital operations and patient flow using the connected clinical data.</p></div><button className="action-button" onClick={newSession}>New session</button></div><div className="assistant-layout"><section className="medical-card conversation"><div className="conversation-header"><div><strong>Clinical conversation</strong><span>Session {sessionId ? sessionId.slice(0,8) : 'connecting'}</span></div><span className="connection-status">Connected</span></div><div className="messages">{messages.map((m,i)=><div className={m.role === 'user' ? 'message user' : 'message'} key={i}><span className="message-label">{m.role === 'user' ? 'You' : 'Assistant'}</span><p>{m.content}</p><time>{m.time}</time></div>)}{loading && <div className="message"><span className="message-label">Assistant</span><p>Reviewing the clinical data...</p></div>}</div><div className="composer"><div className="quick-actions">{quickActions.map((a)=><button key={a} onClick={()=>sendMessage(a)}>{a}</button>)}</div><div className="input-row"><input value={input} onChange={(e)=>setInput(e.target.value)} onKeyDown={(e)=>{if(e.key==='Enter'&&!e.nativeEvent.isComposing&&e.keyCode!==229) sendMessage()}} placeholder="Ask about patient data or hospital flow" disabled={loading}/><button onClick={()=>sendMessage()} disabled={loading}>Send</button></div></div></section><aside className="medical-card guidance"><p className="section-label">Assistant guidance</p><h2>Use clinical questions</h2><p>Ask for operational summaries, ward capacity, patient context, or an explanation of a discharge prediction.</p><dl><div><dt>Connected context</dt><dd>Hospital data services</dd></div><div><dt>Conversation memory</dt><dd>Current session only</dd></div><div><dt>Patient safety</dt><dd>Review before action</dd></div></dl></aside></div></div>
}
