'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { getPatients, getPatient } from '@/lib/api'

export default function ExplorerPage() {
  const [patients, setPatients] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [search, setSearch] = useState(''); const [filterWard, setFilterWard] = useState('ALL WARDS'); const [filterCondition, setFilterCondition] = useState('ANY'); const [selectedPatient, setSelectedPatient] = useState<any>(null)
  const loadPatients = async () => { setLoading(true); try { const params:any = {}; if (search) params.search = search; if (filterWard !== 'ALL WARDS') params.ward = filterWard; if (filterCondition !== 'ANY') params.condition = filterCondition; setPatients(await getPatients(params)) } finally { setLoading(false) } }
  useEffect(() => { loadPatients() }, [search, filterWard, filterCondition])
  return <div><div className="page-heading"><div><p className="section-label">Care coordination</p><h1>Patient registry</h1><p>Review active admissions and open a patient record for clinical context.</p></div><span className="record-count">{patients.length} records</span></div>
    <div className="registry-layout"><div><div className="medical-card filter-card"><label>Search patient<input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Name or patient ID" /></label><label>Ward<select value={filterWard} onChange={(e)=>setFilterWard(e.target.value)}><option>ALL WARDS</option><option>ICU</option><option>CARDIOLOGY</option><option>ORTHOPEDICS</option><option>INTERNAL MEDICINE</option></select></label><label>Condition<select value={filterCondition} onChange={(e)=>setFilterCondition(e.target.value)}><option>ANY</option><option>CRITICAL</option><option>STABLE</option></select></label><button className="action-button" onClick={loadPatients}>Apply filters</button></div>
      <div className="medical-card table-card"><div className="table-title"><strong>Active patient registry</strong><span>Updated from hospital data services</span></div>{loading ? <p className="table-message">Loading patient records...</p> : patients.length === 0 ? <p className="table-message">No patients found.</p> : <div className="table-scroll"><table><thead><tr><th>Patient ID</th><th>Name</th><th>Ward</th><th>Condition</th><th>Status</th><th>Record</th></tr></thead><tbody>{patients.map((p)=><tr key={p.id}><td>{p.patient_id}</td><td><strong>{p.name}</strong></td><td>{p.ward || '—'}</td><td>{p.condition}</td><td><span className={p.is_active ? 'table-status active' : 'table-status'}>{p.is_active ? 'Active' : 'Discharged'}</span></td><td><button className="text-button" onClick={async()=>setSelectedPatient(await getPatient(p.id))}>View</button> <Link className="text-button" href={`/explainability/${p.id}`}>Insights</Link></td></tr>)}</tbody></table></div>}</div></div>
      <aside className="medical-card patient-card">{selectedPatient ? <><p className="section-label">Selected patient</p><h2>{selectedPatient.name}</h2><p className="patient-id">{selectedPatient.patient_id}</p><dl><div><dt>Age</dt><dd>{selectedPatient.age}</dd></div><div><dt>Gender</dt><dd>{selectedPatient.gender}</dd></div><div><dt>Condition</dt><dd>{selectedPatient.condition}</dd></div><div><dt>Status</dt><dd>{selectedPatient.is_active ? 'Active admission' : 'Discharged'}</dd></div></dl><Link href={`/explainability/${selectedPatient.id}`} className="primary-button full-button">View model insights</Link></> : <div className="empty-panel"><p className="section-label">Patient details</p><h2>Select a record</h2><p>Choose a patient from the registry to review admission details and discharge signals.</p></div>}</aside>
    </div></div>
}
